Backend/account/urls.py
from django.urls import path
from . import views

from django.contrib.auth import views as auth_views


app_name = "account"

urlpatterns = [
    # rest api
    path("shopvendor/register/", views.shop_vendor_register_view, name="shop_vendor_register"),
    path("customer/register/", views.customer_register_view, name="customer_register"),
    path("Login_api/", views.login_view, name="API_login"),
    # Logout
    path("logout/", views.logout_req, name="logout"),

    # email send reset password-link
	path('email-link/', views.Reset_password_emailView.as_view(), name=""),




    



    # change password
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="password_reset_form.html"
        ),
        name="password_reset_confirm",
    ),
    # path(
    #     "ResetPasswordComplete/",
    #     auth_views.PasswordResetCompleteView.as_view(
    #         template_name="ResetProcessComplete.html"
    #     ),
       
    # ),

    path(
        "reset-password-complete/",
        auth_views.PasswordResetCompleteView.as_view(template_name="reset_process_complete.html"),
        name="password_reset_complete",
    ),


    
    # account activate link
    path(
        "activate/<slug:uidb64>/<slug:token>/", views.account_activate, name="activate"
    ),


]


# Authentication learning resource
# https://docs.djangoproject.com/en/3.0/topics/auth/default/#all-authentication-views

Backend/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("account.urls")),
    # product category and product
    path("product-inventory/", include("inventory.urls")),
    #  user order management
    path("order/", include("OrderManagement.urls", namespace="OrderManagement")),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Backend/account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    is_customer = models.BooleanField("Is customer", default=False)
    is_vendor = models.BooleanField("Is vendor", default=False)


class ShopVendorProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    vendorname = models.CharField(max_length=100, default="Null")
    Business_name = models.CharField(max_length=100)

    Business_phone = models.CharField(max_length=100)

    Business_address = models.CharField(max_length=100)

    is_active = models.BooleanField(default=True)
    
    def __str__(self):
        return self.vendorname


class CustomerProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)

    Customer_phone = models.CharField(max_length=100)

    Customer_address = models.CharField(max_length=100)

    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f"phone: {self.Customer_phone}, address: {self.Customer_address}"





Backend/account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User

from django.contrib.auth.forms import (
    AuthenticationForm,
    PasswordResetForm,
    SetPasswordForm,
)


class UserLoginForm(AuthenticationForm):

    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control mb-3",
                "placeholder": "Username",
                "id": "login-username",
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "placeholder": "Password",
                "id": "login-pwd",
            }
        )
    )


class VendorSignUpForm(UserCreationForm):
    username = forms.CharField(
        label="Enter Username",
        min_length=4,
        max_length=50,
        help_text="Required",
        widget=forms.TextInput(
            attrs={"class": "form-control mb-3", "placeholder": "Username"}
        ),
    )

    email = forms.EmailField(
        max_length=100,
        help_text="Required",
        error_messages={"required": "Sorry, you will need an email"},
        widget=forms.TextInput(
            {
                "class": "form-control mb-3",
                "placeholder": "E-mail",
                "name": "email",
                "id": "id_email",
            }
        ),
    )

    password1 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(
            {"class": "form-control mb-3", "placeholder": "Password"}
        ),
    )

    password2 = forms.CharField(
        label="Repeat password",
        widget=forms.PasswordInput(
            {"class": "form-control", "placeholder": "Repeat Password"}
        ),
    )

    def clean_email(self):
        email = self.cleaned_data["email"]
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError(
                "Please use another Email, that is already taken"
            )
        return email

    class Meta:
        model = User
        fields = (
            "username",
            "email",
            "password1",
            "password2",
            "is_vendor",
            "is_customer",
        )


class CustomerSignUpForm(UserCreationForm):
    username = forms.CharField(
        label="Enter Username",
        min_length=2,
        max_length=50,
        help_text="Required",
        widget=forms.TextInput(
            attrs={"class": "form-control mb-3", "placeholder": "Username"}
        ),
    )

    email = forms.EmailField(
        max_length=100,
        help_text="Required",
        error_messages={"required": "Sorry, you will need an email"},
        widget=forms.TextInput(
            {
                "class": "form-control mb-3",
                "placeholder": "E-mail",
                "name": "email",
                "id": "id_email",
            }
        ),
    )

    password1 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(
            {"class": "form-control mb-3", "placeholder": "Password"}
        ),
    )

    password2 = forms.CharField(
        label="Repeat password",
        widget=forms.PasswordInput(
            {"class": "form-control", "placeholder": "Repeat Password"}
        ),
    )

    def clean_email(self):
        email = self.cleaned_data["email"]
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError(
                "Please use another Email, that is already taken"
            )
        return email

    class Meta:
        model = User
        fields = (
            "username",
            "email",
            "password1",
            "password2",
            "is_vendor",
            "is_customer",
        )

Backend/account/views.py
from django.shortcuts import redirect, render, HttpResponseRedirect, get_object_or_404
from django.http import HttpResponse

from django.contrib import messages

# Authentication
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, logout, login

# Create your views here.

from .forms import VendorSignUpForm, CustomerSignUpForm
# database model
from .models import ShopVendorProfile, CustomerProfile
from inventory.models import product, Category
from OrderManagement.models import Order


from .models import User

#
from .tokens import account_activation_token

from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes
from django.utils.encoding import force_str
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode

# restapi 
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response

from account.serializers import RegisterSerializer,LoginSerializer,resetpasswordSerializer

# rest frame work authentication
from rest_framework import generics
from rest_framework_simplejwt.tokens import RefreshToken
from rest_framework.permissions import IsAuthenticated

from rest_framework.views import APIView

def get_tokens_for_user(user):
  refresh = RefreshToken.for_user(user)
  return {'access': str(refresh.access_token),}

# register shop vendor user serializer view
@api_view(['POST'])
def shop_vendor_register_view(request):
    if request.method == 'POST':
        userData={}
        userData['email']=request.data['email']
        userData['username']=request.data['username']
        userData['password']=request.data['password']
        userData['password2']=request.data['password2'] 

        print("User data: ",userData)
        
        Business_name=request.data['Business_name']
        Business_phone=request.data['Business_phone']
        Business_address=request.data['Business_address']

        print("Business name", Business_name, "Business phone", Business_phone, "Business address", Business_address)

        serializer = RegisterSerializer(data=userData)
        data = {}
        if serializer.is_valid():
            user = serializer.save()
            user.is_vendor = True
            user.save()

            ShopVendorProfile.objects.create(
                user=user,
                vendorname=user.username,
                Business_name=Business_name,
                Business_phone=Business_phone,
                Business_address=Business_address,
            )

            data['response'] = "successfully registered a new user."
            data['email'] = user.email
            data['username'] = user.username
            data['is_vendor'] = user.is_vendor

            return Response("successfully registered a new user.", status=status.HTTP_201_CREATED)


        else:
            data = serializer.errors
            return Response(data,status=status.HTTP_400_BAD_REQUEST)



# register customer 
@api_view(['POST'])
def customer_register_view(request):
    if request.method == 'POST':
        Customer_phone=request.data['Customer_phone']
        Customer_address=request.data['Customer_address']

        userData={}
        userData['email']=request.data['email']
        userData['username']=request.data['username']
        userData['password']=request.data['password']
        userData['password2']=request.data['password2']        
        print("User data: ",userData)
        serializer = RegisterSerializer(data=userData)
        data = {}
        if serializer.is_valid():
            user = serializer.save()
            user.is_customer = True
            user.save()

            CustomerProfile.objects.create(
                user=user,
                Customer_phone=Customer_phone,
                Customer_address=Customer_address,
            )

            data['response'] = "successfully registered a new customer."
            data['email'] = user.email
            data['username'] = user.username
            data['is_customer'] = user.is_customer

        else:
            data = serializer.errors    
        return Response(data)






# login view
@api_view(['POST'])
def login_view(request):
    if request.method == 'POST':
        print("request data", request.data)
        serializer = LoginSerializer(data=request.data)
        name = request.data['username']
        pas = request.data['password']

        user = authenticate(username=name, password=pas)
        data = {}
        if user is not None:
            data['response'] = "successfully authenticated."
            data['username'] = user.username
            data['is_vendor'] = user.is_vendor
            data['is_customer'] = user.is_customer
            data['tokens'] = get_tokens_for_user(user)
        else:
            data = serializer.errors
        return Response(data)


# change password Link send to email
class Reset_password_emailView(APIView):
  
  def post(self, request, format=None):
    serializer = resetpasswordSerializer(data=request.data)
    serializer.is_valid(raise_exception=True)
    return Response({'msg':'Password Reset link send. Please check your Email'}, status=status.HTTP_200_OK)





def logout_req(request):
    logout(request)
    return redirect("account:mainPage")


def account_activate(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))

        user = User.objects.get(pk=uid)

    except (TypeError, ValueError, OverflowError, user.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return HttpResponse("Successfully activated")
    else:
        return HttpResponse("invalid activation")










Backend/account/templates/ResetProcessComplete.html
<!DOCTYPE html>
<html>
  <head>
    <style>
      .container {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 200px;
      }

      .vertical-center {
        margin: 50;
        position: absolute;
        top: 50%;
      }
    </style>
  </head>

  <body>
    <div class="container">
      <div class="vertical-center">
        <h1>Password reset complete</h1>

        <p>Your password has been set. You may go ahead and log in now.</p>
      </div>
    </div>
  </body>
</html>

Backend/account/templates/account_activation_email.html
{% autoescape off %}
Hi {{ user.user_name }},

Your account has successfully created. Please click below link to activate your account

http://{{ domain }}{% url 'account:activate' uidb64=uid token=token %}
{% endautoescape %}

Backend/account/templates/password_reset.html



<style>
    .account-form input {
        width: 100%;
        border: 2px solid #ccc;
        height: calc(2em + .15rem + 2px);
    }

    .account-form input:focus {
        border-color: #1497ff;
        box-shadow: inset 0 0px 0px rgba(0, 0, 0, 0.075), 0 0 0px rgba(255, 0, 0, 0.6);
    }
</style>

<div class="container-fluid">
    <div class="row no-gutter">
        <div class="col-md-12">
            <div class="login d-flex align-items-center py-5">
                <div class="container">
                    <div class="row">
                        <div class="col-12 col-md-12 mx-auto">
                            <form class="account-form p-4 rounded col-lg-8 mx-auto" method="post" action="#">
                                <p class="h3 mb-4 font-weight-bold">Forgotten your password?</p>
                                    <p>Enter your e-mail address to obtain a new password.</p>
                                    {% if form.errors %}
                                        <div class="alert alert-primary" role="alert">
                                            Error: Please try again!
                                        </div>
                                    {% endif %}
                                    {% csrf_token %}
                                    <label class="small font-weight-bold">{{ form.email.label}}</label>
                                    {{ form.email }}
                                    <button class="btn btn-primary btn-block py-2 mb-4 mt-5 fw-bold w-100" type="submit"value="Send e-mail">Send e-mail</button>
                                    <p class="text-center"><a href="#">Login</a></p>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Backend/account/templates/password_reset_done.html


<style>
  .container {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 200px;
  }

  .vertical-center {
    margin: 50;
    position: absolute;
    top: 50%;
  }
</style>

<div class="container">
  <div class="vertical-center">
    <div id="content" class="colM">
      <h1>Password reset sent</h1>

      <p>
        We’ve emailed you instructions for setting your password, if an account
        exists with the email you entered. You should receive them shortly.
      </p>

      <p>
        If you don’t receive an email, please make sure you’ve entered the
        address you registered with, and check your spam folder.
      </p>

      <br class="clear" />
    </div>
  </div>
</div>


Backend/account/templates/password_reset_form.html
<!DOCTYPE html>
<html>
  <head>
    <style>
      .container-fluid {
        max-width: 100%;
      }

      body {
        margin-bottom: 0px;
      }

      .account-form input {
        border: 2px solid #ccc;
        height: calc(2em + 0.75rem + 2px);
      }

      .account-form input:focus {
        border-color: #1497ff;
        box-shadow: inset 0 0px 0px rgba(0, 0, 0, 0.075),
          0 0 0px rgba(255, 0, 0, 0.6);
      }
    </style>
  </head>

  <body>
    <div class="container-fluid">
      <div class="row no-gutter">
        <div class="col-md-6 bg-light">
          <div class="login d-flex align-items-center py-5">
            <div class="container">
              <div class="row">
                <div class="col-12 col-md-12 mx-auto">
                  <form class="login-form p-4 rounded" method="post">
                    {% csrf_token %}
                    <h1 class="h4 mb-4 font-weight-bold">
                      Change your password
                    </h1>
                    <p>Use the form below to change your password.</p>

                    {% if form.errors %}
                    <div class="alert alert-primary" role="alert">
                      Error: Please try again!
                    </div>
                    {% endif %}

                    <label class="small font-weight-bold"
                      >{{ form.new_password1.label}}</label
                    >
                    {{ form.new_password1 }}
                    <br />
                    <label class="small font-weight-bold"
                      >{{ form.new_password2.label}}</label
                    >
                    {{ form.new_password2 }}
                    <ul>
                      <li>
                        Your password can’t be too similar to your other
                        personal information.
                      </li>
                      <li>Your password must contain at least 8 characters.</li>
                      <li>Your password can’t be a commonly used password.</li>
                      <li>Your password can’t be entirely numeric.</li>
                    </ul>
                    <button
                      class="btn btn-primary btn-block py-2 mb-4 mt-5 font-weight-bold"
                      type="submit"
                      value="Change"
                    >
                      Submit
                    </button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-6 d-none d-md-flex bg-image"></div>
      </div>
    </div>
  </body>
</html>

Backend/account/templates/reset_process_complete.html
<style>
  .container {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 200px;
  }

  .vertical-center {
    margin: 50;
    position: absolute;
    top: 50%;
  }
</style>

<div class="container">
  <div class="vertical-center">
    <h1>Password reset complete</h1>

    <p>Your password has been set. You may go ahead and log in now.</p>
  </div>
</div>